### ISSUE TITLE
Shows Invalid signature: oauth_signature 

### ISSUE THREAD

**Issue by PrashantKT** [NicholasBellucci/FatSecretSwift#5]
When Search query has  rounded bracket it shows 

{
    "error": {
        "code": 8,
        "message": "Invalid signature: oauth_signature ' k/wjjCPg8Oewc4zlFctMYCPOuA='"
    }
}

Search query is **coco-cola classic (12 oz)** 

If I only search  **coco-cola classic** it is working but when I add rounded bracket it shows error

Please help

**Comment by NicholasBellucci** [comment]
I have fixed this by allowing reserved characters to be in a search expression. These characters are defined here: https://tools.ietf.org/html/rfc3986#section-2.2 . You should be able to just pull down the updates.

**Comment by phiren** [comment]
Hi Can you also add % to reserved characters?
Because when I search like "theo chocolate organic fair trade pure 85% dark chocolate", it does not work.

**Comment by NicholasBellucci** [comment]
@phiren I just noticed this and will add it.

**Comment by NicholasBellucci** [comment]
Should be fixed as of https://github.com/NicholasBellucci/FatSecretSwift/pull/6
