### ISSUE TITLE
Request this be changed to use secure connection

### ISSUE THREAD

**Issue by tappready** [NicholasBellucci/FatSecretSwift#8]
https://github.com/NicholasBellucci/FatSecretSwift/blob/3bd0b8b3fc1c88a96aa4d8b582563a85f9259e24/Sources/FatSecretSwift/FatSecretParams.swift#L17

**Comment by NicholasBellucci** [comment]
@tappready should be good to go! https://github.com/NicholasBellucci/FatSecretSwift/commit/615d69086a2feb1acfdf1a248e43479cfe657920
